truncate acc_ctegory_master;
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Nutrition','Nutrition','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','FMCG','FMCG','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Gourmet','Gourmet','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Medical','Medical','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Lens & HCD','Lens & HCD','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Pets','Pets','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Toys','Toys','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Exclusives','Exclusives','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Vente','Vente','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Non PSP','Non PSP','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','Services','Services','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','BD Kolkata','BD Kolkata','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Revenue from Operations','BD Mumbai','BD Mumbai','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Income','Interest on FD','Interest on FD','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Income','Amazon recoveries','Amazon recoveries','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Income','Sundry balances w/off','Sundry balances w/off','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Nutrition','Nutrition','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','FMCG','FMCG','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Gourmet','Gourmet','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Medical','Medical','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Lens & HCD','Lens & HCD','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Pets','Pets','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Toys','Toys','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Exclusives','Exclusives','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Vente','Vente','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Non PSP','Non PSP','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','Services','Services','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','BD Kolkata','BD Kolkata','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Purchases of Stock-in-Trade','BD Mumbai','BD Mumbai','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Directors Remuneration','Directors Remuneration','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Salaries, Bonus & Allowances','Direct','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Salaries, Bonus & Allowances','Warehouse','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Salaries, Bonus & Allowances','Others','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Contribution to PF & ESI','Direct','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Contribution to PF & ESI','Warehouse','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Contribution to PF & ESI','Others','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Gratuity','Direct','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Gratuity','Warehouse','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Gratuity','Others','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Staff Welfare','Direct','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Staff Welfare','Warehouse','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Employee Benefit Expenses','Staff Welfare','Others','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Nutrition','Nutrition','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','FMCG','FMCG','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Gourmet','Gourmet','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Medical','Medical','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Lens & HCD','Lens & HCD','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Pets','Pets','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Toys','Toys','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Exclusives','Exclusives','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Vente','Vente','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Non PSP','Non PSP','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','Services','Services','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','BD Kolkata','BD Kolkata','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Market place fees','BD Mumbai','BD Mumbai','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Finance Costs','Interest - Bank ','Interest - Bank ','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Finance Costs','Interest - Others','Interest - Others','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Finance Costs','Loan Processing Fees','Loan Processing Fees','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Depreciation and Amortization','Depreciation and Amortization','Depreciation and Amortization','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Freight and Delivery & Handling Charges','Freight and Delivery & Handling Charges','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Storage Fees','Storage Fees','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Commission on Sales','Commission on Sales','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Brokerage','Brokerage','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Transporation Charges','Transporation Charges','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Loading & Unloading','Loading & Unloading','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Packing Expenses','Packing Expenses','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Rent','Rent','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Insurance ','Insurance ','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Rates & Taxes','Rates & Taxes','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Audit Fees','Audit Fees','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Bank Charges','Bank Charges','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Business Promotion','Business Promotion','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Security Charges','Security Charges','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Computer Expenses','Computer Expenses','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Electricity Expenses','Electricity Expenses','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Foreign Exchange Fluctuation','Foreign Exchange Fluctuation','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Travelling & Conveyance ','Travelling & Conveyance ','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Telephone and Internet Expenses','Telephone and Internet Expenses','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Printing & Stationery','Printing & Stationery','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Professional Fees','Professional Fees','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Postage & Courier','Postage & Courier','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Recruitment Fees','Recruitment Fees','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Repairs & Maintenance','Repairs & Maintenance','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Interest on Delayed Payment of Taxes','Interest on Delayed Payment of Taxes','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Website Expenses','Website Expenses','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','ITC Reversal / Sales Tax Paid','ITC Reversal / Sales Tax Paid','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Other Expenses','Miscellaneous Expenses','Miscellaneous Expenses','approved');
insert into acc_category_master (category_1,category_2,category_3,status) values ('Tax Expense','Tax Expense','Tax Expense','approved');
